version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:10.1.0-1.73.0
    steps:
      - run:
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Ishiko/C++ Platform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/platform.git && cd platform/build/GNUmakefile && make
      - run:
          name: "Install build dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/GNUmakefile && make
      - run:
          name: "Install build dependency: Ishiko/C++ Types"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/types.git && cd types/build/GNUmakefile && make
      - run:
          name: "Install build dependency: Ishiko/C++ Text"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/text.git && cd text/build/GNUmakefile && make
      - run:
          name: "Install build dependency: Ishiko/C++ FileSystem"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/filesystem.git && cd filesystem/build/GNUmakefile && make
      - run:
          name: "Install build dependency: Ishiko/C++ Collections"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/collections.git && cd collections/build/GNUmakefile && make
      - checkout:
          path: /projects/ishiko/cpp/diff
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/diff/Makefiles/GNUmakefile && make
      - run:
          name: "Install test dependency: Ishiko/C++ Process"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Tests"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/tests.git && cd tests/core/build/GNUmakefile && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/diff/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/diff/Tests/Makefiles/GNUmakefile && ./IshikoDiffTests
